# General configuration
algorithm = "ng"  # Can be "ng" for Neural Gas or "gng" for Growing Neural Gas
neurons_n = 200  # Number of neurons
max_iterations = "auto"  # Number of iterations per epoch, "auto" uses the size of the dataset
global_iterations = 3  # Number of epochs
plot_interval = 50  # Interval for saving plots

# Neural Gas specific parameters
epsilon = 0.2  # Learning rate
lambda = 0.5 
lifetime = 50  # Maximum age of connections

# Growing Neural Gas specific parameters
eps_b = 0.1  # Learning rate for the best matching unit
eps_n = 0.001  # Learning rate for the neighboring units
alpha = 0.5  # Error reduction factor for winner neuron
decay = 0.0005  # General error reduction factor

# Default data source
data = "c:/Users/Zayan/Documents/code/personal_repos/ufa_to_ufa/data/dataset1.png"